"""Add is_active field to User model

Revision ID: 024eaae33f3e
Revises: aa38c6d4e333
Create Date: 2025-05-04 20:19:27.749531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '024eaae33f3e'
down_revision = 'aa38c6d4e333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'course', 'user', ['school_super_admin_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'user', ['school_super_admin_id'], ['id'])
    op.add_column('user', sa.Column('role', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'role_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    # ### end Alembic commands ###
