"""Add address field to SchoolAdmin

Revision ID: 188fe94259ec
Revises: e4cc3593d5ea
Create Date: 2025-05-01 10:37:48.620385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188fe94259ec'
down_revision = 'e4cc3593d5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_admin', sa.Column('address', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'school_admin', 'user', ['school_super_admin_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_column('school_admin', 'address')
    # ### end Alembic commands ###
