"""Add Course model

Revision ID: 32a40c202cab
Revises: 188fe94259ec
Create Date: 2025-05-01 12:46:15.546724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a40c202cab'
down_revision = '188fe94259ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_foreign_key(None, 'school_admin', 'user', ['school_super_admin_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_table('course')
    # ### end Alembic commands ###
