"""Update role column to String(30), not nullable, with default

Revision ID: aa38c6d4e333
Revises: fa0dc95702a9
Create Date: 2025-05-04 20:16:06.046925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa38c6d4e333'
down_revision = 'fa0dc95702a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'course', 'user', ['school_super_admin_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'user', ['school_super_admin_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'school', ['school_id'], ['id'])
    op.add_column('user', sa.Column('role_name', sa.String(length=30), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('user', 'role_name')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    # ### end Alembic commands ###
