"""Add role mode

Revision ID: b29565d7b99a
Revises: 024eaae33f3e
Create Date: 2025-05-04 21:41:21.077936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29565d7b99a'
down_revision = '024eaae33f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'course', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'course', 'user', ['school_super_admin_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'school_admin', 'user', ['school_super_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'school_admin', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_table('roles')
    # ### end Alembic commands ###
