"""Add SchoolAdmin model

Revision ID: e4cc3593d5ea
Revises: 52c7ab8cbac7
Create Date: 2025-04-30 21:02:48.996247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cc3593d5ea'
down_revision = '52c7ab8cbac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('state_of_origin', sa.String(length=100), nullable=True),
    sa.Column('local_government', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('step', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('employment_date', sa.Date(), nullable=True),
    sa.Column('social_media', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('posts', sa.Text(), nullable=True),
    sa.Column('school_super_admin_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['school_super_admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_admin')
    # ### end Alembic commands ###
